controller:
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
      service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "10"
      service.beta.kubernetes.io/do-loadbalancer-certificate-id: 98e61172-5967-4b5e-b7c1-629e147f27e2
      service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
      # XXX fluentd breaks with SSL_connect returned=1 errno=0 state=error: tlsv1 alert protocol version (OpenSSL::SSL::SSLError)
      #service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    targetPorts:
      https: 80
