apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-server
  labels:
    app: session-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-server
  template:
    metadata:
      labels:
        app: session-server
    spec:
      volumes:
        - name: secret-ssh-keys
          secret:
            secretName: ssh-keys
        - name: tmate-unix-sockets
          emptyDir: {}
      containers:
        - name: tmate-ssh-server
          image: tmate/tmate-ssh-server:latest
          args: [-k,/etc/tmate-keys,-x,localhost]
          securityContext:
            capabilities:
              add: [SYS_ADMIN] # needed to spawn containers (CLONE_NEWPID, etc.)
          ports:
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: secret-ssh-keys
              readOnly: true
              mountPath: /etc/tmate-keys
            - name: tmate-unix-sockets
              mountPath: /tmp/tmate/sessions
        - name: tmate-proxy
          image: tmate/tmate-proxy:latest
          ports:
            - containerPort: 4001
              name: websocket
            - containerPort: 4002
              name: daemon
          volumeMounts:
            - name: secret-ssh-keys
              readOnly: true
              mountPath: /etc/tmate-keys
            - name: tmate-unix-sockets
              mountPath: /tmp/tmate/sessions
---
kind: Service
apiVersion: v1
metadata:
  name: session-server
spec:
  selector:
    app: session-server
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  - name: websocket
    port: 4001
    targetPort: websocket
