apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
        prometheus.io/path: '/metrics'
    spec:
      volumes:
      - name: secret-pg
        secret:
          secretName: pg
      containers:
      - name: tmate-master
        image: tmate/tmate-master:latest
        ports:
        - containerPort: 4000
          name: http
        - containerPort: 9100
          name: http-metrics
        env:
        - name: MASTER_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: master_base_url
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: misc
              key: secret_key_base
        - name: USE_PROXY_PROTOCOL
          value: "1"
        - name: MASTER_WSAPI_KEY
          valueFrom:
            secretKeyRef:
              name: misc
              key: wsapi_key
        - name: PG_URI
          valueFrom:
            secretKeyRef:
              name: pg
              key: pg_uri
        - name: PG_POOLSIZE
          value: "10"
        - name: PG_SSL_CA_CERT
          value: /etc/ssl/pg/pg_ca.crt
        - name: ERL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ERL_COOKIE
          valueFrom:
            secretKeyRef:
              name: misc
              key: erl_cookie
        volumeMounts:
        - name: secret-pg
          mountPath: /etc/ssl/pg
---
kind: Service
apiVersion: v1
metadata:
  name: master
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "10"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: e119b987-4e70-44eb-a577-ce49d50d668a
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  selector:
    app: master
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
